name: Deploy Airflow DAG

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      # Store AWS credentials securely using Secrets Manager
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      # Replace with your EC2 instance details
      EC2_HOST: "ec2-your-instance-id.compute-region.amazonaws.com"
      EC2_USER: "ec2-user"  # Replace with actual user if needed
      REMOTE_DAG_DIR: "/path/to/airflow/dags"  # Location on EC2

    steps:
      - uses: actions/checkout@v3

      - name: Upload SSH key (required)
        uses: webdevops/ssh-key-upload@v2.0.1
        with:
          # Replace with the path to your .pem file
          ssh_key_path: "~/.ssh/your_key.pem"
          # Optional: Set a passphrase if your key has one
          passphrase: ${{ secrets.PEM_PASSPHRASE }}  # Store passphrase in Secrets Manager (optional)

      - name: Install dependencies on EC2
        run: |
          ssh -i ~/.ssh/your_key.pem ${{ env.EC2_USER }}@${{ env.EC2_HOST }} << EOF
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt install python3-venv
          mkdir environments
          sudo python3 -m venv environments/airflow_env
          sudo source environments/airflow_env/bin/activate
          sudo environments/airflow_env/bin/python3 environments/airflow_env/bin/pip install pandas
          sudo environments/airflow_env/bin/python3 environments/airflow_env/bin/pip install s3fs
          sudo environments/airflow_env/bin/python3 environments/airflow_env/bin/pip install apache-airflow
          EOF

      - name: Upload DAG and support files
        run: |
          scp -i ~/.ssh/your_key.pem twitter_dag.py twitter_etl.py ${{ env.EC2_USER }}@${{ env.EC2_HOST }}:{{ env.REMOTE_DAG_DIR }}

      - name: (Optional) Restart Airflow scheduler on EC2
        run: |
          ssh -i ~/.ssh/your_key.pem ${{ env.EC2_USER }}@${{ env.EC2_HOST }} "sudo airflow dags clear && sudo airflow schedulers restart"
